## Install Required Libraries

In [1]:
pip install pandas numpy

Requirement already satisfied: pandas in C:\Users\91943\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.2)
Requirement already satisfied: numpy in C:\Users\91943\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\91943\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\91943\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\91943\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\91943\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

## Load Dataset

In [2]:
# importing pandas and Numpy
import pandas as pd
import numpy as np

In [3]:
file_path = "data/raw/bakery_sales.csv"
df = pd.read_csv(file_path)

In [4]:
df.head()

   Transaction           Item         date_time period_day weekday_weekend
0            1          Bread   10/30/2016 9:58    morning         weekend
1            2   Scandinavian  10/30/2016 10:05    morning         weekend
2            2   Scandinavian  10/30/2016 10:05    morning         weekend
3            3  Hot chocolate  10/30/2016 10:07    morning         weekend
4            3            Jam  10/30/2016 10:07    morning         weekend

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20507 entries, 0 to 20506
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Transaction      20507 non-null  int64
 1   Item             20507 non-null  object
 2   date_time        20507 non-null  object
 3   period_day       20507 non-null  object
 4   weekday_weekend  20507 non-null  object
dtypes: int64(1), object(4)
memory usage: 801.2+ KB

## Understand Dataset

In [6]:
df.isnull().sum()

Transaction        0
Item               0
date_time          0
period_day         0
weekday_weekend    0
dtype: int64

In [7]:
df.describe()

        Transaction
count  20507.000000
mean    4976.202370
std     2796.203001
min        1.000000
25%     2552.000000
50%     5137.000000
75%     7357.000000
max     9684.000000

In [8]:
df.columns

Index(['Transaction', 'Item', 'date_time', 'period_day', 'weekday_weekend'], dtype='object')

## Data Cleaning

In [9]:
# Remove duplicates and create a fresh copy
df = df.drop_duplicates().copy()

In [10]:
# Convert date_time column
df['date_time'] = pd.to_datetime(df['date_time'])

In [11]:
# Create New Time Columns
df['Date'] = df['date_time'].dt.date
df['Month'] = df['date_time'].dt.month
df['Hour'] = df['date_time'].dt.hour
df['Day_Name'] = df['date_time'].dt.day_name()

In [12]:
# Standardize Text Columns
df['Item'] = df['Item'].str.strip().str.title()
df['period_day'] = df['period_day'].str.strip().str.lower()
df['weekday_weekend'] = df['weekday_weekend'].str.strip().str.lower()

In [14]:
# Save cleaned dataset
df.to_csv('data/cleaned/cleaned_bakery_sales.csv', index=False)